export const POSTS_FETCHED = 'POSTS_FETCHED'
export const POST_FETCHED = "POST_FETCHED"

export const LIKE_POSTS = 'LIKE_POSTS'
export const UNLIKE_POSTS = "UNLIKE_POSTS"

export const USER_LOGGED_IN = "USER_LOGGED_IN"
export const USER_LOGGED_OUT = "USER_LOGGED_OUT"
export const USER_ACTIVATE_CODE = "USER_ACTIVATE_CODE"
