export const POSTS_FETCHING = "POSTS_FETCHING"
export const POSTS_ERROR = "POSTS_ERROR"
export const POSTS_FETCHED = 'POSTS_FETCHED'
export const POST_FETCHED = "POST_FETCHED"

export const LIKE_POSTS = 'LIKE_POSTS'
export const UNLIKE_POSTS = "UNLIKE_POSTS"

export const USER_LOGGED_IN = "USER_LOGGED_IN"
export const USER_LOGGED_OUT = "USER_LOGGED_OUT"
export const USER_ACTIVATE_CODE = "USER_ACTIVATE_CODE"

export const USER_SIGN_UP = "USER_SIGN_UP"
export const FETCH_USER = "FETCH_USER"

export const COMMENTS_FETCHED = "COMMENT_FETCHED"
export const COMMENTS_ERROR = "COMMENT_ERROR"
export const COMMENT_READY = "COMMENT_READY"

export const CREATE_TWIG = "CREATE_TWIG"
export const FETCHED_TWIGS = "FETCHED_TWIGS"
export const FETCHING_ERROR = "FETCHING_ERROR"
